#!/bin/bash
cd ~;
mkdir tmp;
cd tmp;
auracle sync | while read -r name; do
    name=($name)
    name=${name[0]}
    echo "$name";
    auracle clone "$name";
    cd "$name";
    makepkg -sirc --noconfirm;
    cd ..;
    rm -rf "$name";
done
pacman -Qqm | while read -r name; do
    if [[ "$name" = "st-git" ]]; then
        echo "$name";
        echo "Skipping st";
    elif [[ "$name" = *"git"* ]]; then
        echo "$name";
        auracle clone "$name";
        cd "$name";
        makepkg -sirc --noconfirm;
        cd ..;
        rm -rf "$name";
    fi
done
cd ~;
rmdir tmp;
